[mypy]
mypy_path = src
explicit_package_bases = True

strict = True

warn_return_any = True 
disallow_untyped_defs = True 
no_implicit_optional = True  
check_untyped_defs = True 
ignore_missing_imports = True 

warn_unused_ignores = True 
warn_redundant_casts = True
warn_unreachable = True 
strict_equality = True 