[mypy]
python_version = 3.8
mypy_path = src
explicit_package_bases = True

strict = True

no_implicit_optional = True  
ignore_missing_imports = True 
warn_unreachable = True 
strict_equality = True 

[mypy-tests.*]
ignore_errors = True 