[project]
name = "search_kinopoisk_api"
version = "1.0.0"
description = "kinopoisk_search"
requires-python = ">=3.8"

dependencies = [
    "fastapi[all]==0.111.0",
    "pydantic-settings<=2.2.1",
    "pydantic<=2.6.1",
    "httpx",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
    "flake8", 
    "flake8-pyproject",
    "black",
    "pycodestyle", 
    "pydocstyle",
    "mypy",
    "pre-commit==3.5.0",
    "ruff==0.3.0",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]


[tool.coverage.run]
source = [
    "app",
    "core",
    "domain",
]
omit = [
    "**/.mypy_cache/*",
    "tests/*",
    "**/__pycache__/*",
]

[project.scripts]
app = "app.main:run"
