[pytest]
pythonpath = src
testpaths = tests
asyncio_default_fixture_loop_scope = "function"
markers =
    api: marks tests as integration tests (deselect with '-m "not api"')
    unit: marks tests as unit tests (deselect with '-m "not unit"')

filterwarnings =
    ignore: Please use `import python_multipart` instead:PendingDeprecationWarning
